### PR TITLE
Add tagging support

### PR DESCRIPTION
**Pull request by ToMe25**
This pull request adds the ability to tag the new commit in the same action, by supplying it with a tag name.

If you don't think this matches what this action is meant to do feel free to close this pr.

### CODE REVIEW

**Comment by EndBug** [comment]
Hey, thanks for the PR! I'll look into it as soon as I can ;)

**Comment by EndBug** [comment]
Hey, I've added this in `v4.2.0` (also available via the `v4` and `latest` refs)
Just a note: if a tag already exists it will be updated, which is different from what you have originally coded: I hope this works out for you, but I guess the majority of people would prefer it like this, since workflows are made to run multiple times, and I see how tagging builds and so would be easier this way.
Thanks again for the PR :)

**Comment by ToMe25** [comment]
Yes, thats probably the better way.
I wont be able to use this action, as after i created this pr,
i figured out that what i wanted conflicts with the intention(and implementation) of this action.
I have found another way to do it, and hope this addition will help other people :)

**Comment by EndBug** [comment]
@all-contributors please add @ToMe25 for code and ideas

**Pull request merged**
