### PR TITLE
add check to allow empty commits if arg is set

### PR DESCRIPTION
**Pull request by mcargille**
Modifies the changed files check to continue the process if the '--allow-empty' argument was passed, even if no files were changed.

### CODE REVIEW

**Comment by mcargille** [comment]
Tested and working in one of my private repositories

**Comment by mcargille** [comment]
resolves #350

**Review by EndBug — CHANGES_REQUESTED** [review]
Hi, thanks for submitting the PR! 
I've left a couple of suggestions ;)

**Review by EndBug — APPROVED** [review]

**Comment by EndBug** [comment]
@please add @mcargille for their bug report and code contribution

**Comment by EndBug** [comment]
@all-contributors please add @mcargille for their bug report and code contribution

**Comment by EndBug** [comment]
This fix has been published in `v8.0.1` (also `v8` and `latest`). Thanks again for your contribution ❤️

**Pull request merged**
