### PR TITLE
add option to use --signoff with git commit

### PR DESCRIPTION
**Pull request by pvogt09**
This PR adds the ability to `--signoff` the created commit by introducing a new options `signoff`.

### CODE REVIEW

**Comment by pvogt09** [comment]
I have tested it by changing the `build.yml` to use the local version of the action and the result was https://github.com/pvogt09/add-and-commit/actions/runs/187259492/workflow which passed and created a commit with the desired commit message and "Signed-off-by" line. For the PR I deleted these commits again and force pushed a more tidyer version. I just recreated the local test in https://github.com/pvogt09/add-and-commit/tree/test.

The aim of the `signoff` flag is not to change `git add` (that does not have a `--signoff` argument btw), it is supposed to add "Signed-off-by: author < email-address >" to the commit message (like in 0cbe3c6). It might be possible to archieve the same with the `message` option, but then author and email of the push/pull_request that started the workflow have to be known in advance and can not be changed/dynamically derived.

**Comment by EndBug** [comment]
Sorry, my bad:
- When I meant that it wasn't committing correctly I meant that it didn't do it correctly **when the option was not being used**.
- You're right, that goes to the `git commit` command, using a dedicated option is ok

**Comment by pvogt09** [comment]
I am ok with the changes. Thank you for the help.

**Comment by EndBug** [comment]
@all-contributors please add @pvogt09 for code

**Comment by EndBug** [comment]
Ok, you can find the new feature in version `v4.3.0` (available also using `v4` and `latest`)

Thanks again for your contribution ✨

**Pull request merged**
