### PR TITLE
Try: Use github.actor as default value for commit author

### PR DESCRIPTION
**Pull request by ocean90**
With regards to #126 and #125 I was wondering if we can't use a better default value. Looking at the docs I found `github.actor` in the [GitHub context](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context) which is "The login of the user that initiated the workflow run" which is basically the committer name.

Some actions/workflows are already using this:

* https://github.com/marketplace/actions/create-pull-request#action-inputs
* https://github.com/marketplace/actions/configure-git-credentials#inputs
* https://github.com/google/site-kit-wp/blob/develop/.github/workflows/storybook.yml#L87-L90

The PR is ~currently untested,~ open for discussion, and needs some sanity checks.

The current API request was added in #49 for PR support.

### CODE REVIEW

**Comment by ocean90** [comment]
I have used the forked action in a private repo and it's working fine so far.

**Comment by EndBug** [comment]
Sorry if I couldn't take a look at this before.
I have a question: what if I manually trigger the workflow on a commit by someone else? The current action would pick the commit author, while your change would look at me, since I'm the one that started the run. Am I right?

**Comment by ocean90** [comment]
That's correct. I think this is a better behavior than before?

**Comment by EndBug** [comment]
Seems fair
As soon as I'll be able to test this it will be added as a major change then 👍🏻

**Comment by EndBug** [comment]
@all-contributors please add @ocean90 for their code

**Comment by EndBug** [comment]
Introduced in [`v7.0.0`](https://github.com/EndBug/add-and-commit/releases/tag/v7.0.0) (`v7`, `latest`)

Thanks for the PRs!

**Pull request merged**
